# Generated by Django 2.0.4 on 2018-04-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('codigo', models.IntegerField()),
                ('tipo', models.CharField(max_length=255)),
                ('cantidad', models.IntegerField()),
                ('estado', models.TextField()),
            ],
        ),
    ]
