# Generated by Django 2.0.4 on 2018-04-29 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoRegistro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='codigo',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='dispositivoregistro',
            name='dispositivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.Dispositivo'),
        ),
        migrations.AddField(
            model_name='dispositivoregistro',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.Estudiante'),
        ),
    ]
