# Generated by Django 2.0.4 on 2018-04-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_auto_20180429_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositivo',
            name='codigo',
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='serial',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
