# Generated by Django 2.0.4 on 2018-04-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_auto_20180429_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='serial',
            field=models.CharField(max_length=255),
        ),
    ]
