# Generated by Django 2.0.4 on 2018-04-30 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_auto_20180429_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivoregistro',
            name='cantidad',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dispositivoregistro',
            name='estado',
            field=models.TextField(default='Bueno'),
            preserve_default=False,
        ),
    ]
